name: Go Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DB_FILE: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Run migrations
        working-directory: ./internal/db/migrations
        run: goose sqlite3 ./${{ env.DB_FILE }} up

      - name: Install dependencies
        run: /usr/local/go/bin/go mod download

      - name: Build
        env:
          CC: aarch64-linux-gnu-gcc
          GOOS: linux
          GOARCH: arm64
        run: /usr/local/go/bin/go build -v -o myapp ./cmd/api/main.go

      - name: Stop existing service
        run: sudo systemctl stop myapp.service || true
        continue-on-error: true

      - name: Deploy application
        env:
          APP_PORT: ${{ secrets.APP_PORT }}
        run: sudo -u volen bash scripts/deploy.sh

      - name: Verify deployment
        run: |
          sleep 30
          sudo systemctl status myapp.service
